### ISSUE TITLE
chimee-kernel 默认应该支持 native 不是 mp4

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee-kernel#1]
[selectKernel 方法](https://github.com/Chimeejs/chimee-kernel/blob/master/src/index.js#L45-L70)中判断默认应该为 native 而非 mp4 ，用户可能不添加 mp4 的 kernel。

chimee 层现在锁定版本为 1.0.9。

**Comment by songguangyu** [comment]
chimee-kernel 1.0.11 fixed it.

**Comment by toxic-johann** [comment]
https://github.com/Chimeejs/chimee-kernel/blob/master/src/index.js#L45-L79

感觉这个逻辑还是有问题。。。我没有传入 box 和 src。理应还是有 native kernel 垫底的啊。

我新建一个 video ，不一定要传 src 啊。。。

**Comment by songguangyu** [comment]
close
