### ISSUE TITLE
建议移除 Kernel 内部超时重试逻辑

### ISSUE THREAD

**Issue by huzunjie** [Chimeejs/chimee-kernel#7]
前面特意增加了box判断，针对hls禁用超时处理逻辑，不再自动refresh（但判断条件错误 this.box !== 'hls' 应为 this.config.box !== 'hls'）。

相关代码：https://github.com/Chimeejs/chimee-kernel/blob/master/src/index.js#L115

现在发现flv容器下refresh也存在异常：flv内部拉流解码处理不够纯洁，再次热重试会解码异常；而kernel内的超时时长为1.5秒远小于chimee的重试逻辑的3秒以上，也从而会导致chimee的重试逻辑执行之前就挂掉了。

Demo 参见：http://chimee.org/demo/live-clarity.html?flv 。
在控制条中进行流切换（日志见控制台）。

综上，kernel中的timeout判断逻辑建议移除，所以reloadTime也就不需要了。

注意：首次加载非动态切流操作时chimee走的load而不是silentLoad，移除掉kernel的重试逻辑会导致此场景无重试策略。

**Comment by songguangyu** [comment]
done in version 1.1.0
